const appname = "E_Commerce_App";
const appversion = "Version 1.0.0";
const credits = "@Abdul Khaliq";
const email = "Email";
const emailHint = "admin@admin.com";
const password = "Password";
const retypepassword = "Retype Password";
const passwordHint = "******";
const name = "Name";
const nameHint = "Abdul Khaliq";
const forgetpassword = "Forget  Password";
const login = "Log in";
const signup = "Sign up";
const createanewaccount = "or, create a new account";
const loginwith = "Login with";
const privacypolicy = "Privacy Policy";
const termsandconditions = "Terms and Conditions";
const alreadyhaveanaccount = "Already have an account?";
const home = "Home",
    categories = "Categories",
    cart = "Cart",
    loggedin = "Logged in Successfully",
    loggedout = "Logged out Successfullu",
    account = "Account";
const searchanything = "Search Anything",
    todaydeals = "Today's Deal",
    flashsale = "Flash  Sale",
    topsellers = "Top Sellers",
    brands = "Brand",
    topcategories = "Top Categories",
    featuredcategories = "Featured Categories",
    womendressing = "Women Dress",
    girlswatch = "Girls Watch",
    girlsdress = "Girls Dress",
    mobilephone = "Mobile Phone",
    featuredproducts = "Featured Products",
    tshirts = "TShirst",
    boysglasses = "Boys Glasses";
//
const womenclothing = "Women Clothing",
    computerandAccessories = "Computer and Accessories",
    automobiles = "Auto Mobile",
    kidtoys = "Kid & Toys",
    sports = "Sports",
    jewelery = "Jewelery",
    cellphone = "Cell Phone & Tab",
    furniture = "Furniture",
    menclothingandfashion = "Men Clothing & Fashion";

const video = "Video",
    sellerpolicy = "Seller Policy",
    returnpolicy = "Return Policy",
    supportpolicy = "Support Policy",
    reviews = "Reviews";

const wishlist = "My Wish List", messages = "Messages", orders = "My Orders";
